### ISSUE TITLE
.github: workflows: probably shouldn't skip tests when PR found

### ISSUE THREAD

**Issue by ee7** [zighelp/zighelp#34]
Hey @rofrol. Thanks for all the nice work on zighelp.

I noticed that it looks like tests currently don't run on push to `master` if the merged commit came from a PR (follow up from commit https://github.com/zighelp/zighelp/commit/e9766e6638d077076ce0db85de3f5fb884dae3ad): 

https://github.com/zighelp/zighelp/blob/febf8d2317fd630ea19257faa7a9058ebb735661/.github/workflows/push_on_master.yml#L30-L39

I couldn't immediately see in [`8BitJonny/gh-get-current-pr`](https://github.com/8BitJonny/gh-get-current-pr) when `pr_found` is false, but this looks suspicious to me. We can only be confident that testing the PR branch produces the same outcome as the `master` branch if both of these are true:

1. The PR is up to date with `master` at merge time. That is, the PR branch needs to either be based on the latest `master` commit, or have a merge commit with the latest `master` state. There are GitHub repo settings that enforce this, and that CI must pass on the PR branch.
1. The testing workflow is fully deterministic. This requires e.g. the version of every dependency to be pinned, such that running the same workflow at a later date should produce the same outcome. This is difficult to fully achieve on GitHub unless you run the tests in a container, because the contents of e.g. the `ubuntu-22.04` image change constantly.

Does `needs.pr.outputs.pr_found` evaluate to `true`, and therefore cause the tests to be skipped, when the merged PR was not up to date with `master`?

Even if not, skipping tests could still produce a problem with item 2 above. It looks like CI in this repo only takes a minute or two, so I'd suggest just running tests unconditionally on push to `master`.

Thoughts?

Edit: Oh, sorry - I just saw that the last few PRs were merged via the merge queue. Maybe that's sufficient if it's guaranteed that every PR is merged via the queue.

**Comment by rofrol** [comment]
Thanks.
Maybe I will also replace this push_on_master.yml with pr_merged.yml and then run deploy.

The problem with Github Actions is that you cannot have info if merge if from PR at the workflow level.

So now the docker vms are started for tests when there is no need for that. But I can't check that earlier.

Also Github Actions don't have [downstream pipelines](https://docs.gitlab.com/ee/ci/pipelines/downstream_pipelines.html), so that I can decide what workflow would be next.

So anyway, this push_on_master.yml was only for me when I was pushing directly to master, but there are some nice upside with merge queue, so it is better to have every commit going through PR.

Thanks again :)
